### ISSUE TITLE
Buggy prompt

### ISSUE THREAD

**Issue by zephyr111** [netorcai/netorcai#6]
The default prompt cause the terminal to behave weirdly when netorcai ends on Debian testing using gnome-terminal.
By weirdly, I mean that the new line does not work anymore and no input keys can be seen within the terminal. 
It does not occur with --simple-prompt.
Moreover the completion popup cannot be closed.

**Comment by mpoquet** [comment]
I can reproduce similar error with e4ac8e7 and my setup (sakura with a customized zsh) thanks to the following scenario.
1. In terminal1, launch netorcai (`netorcai`)
2. In terminal2, kill netorcai (`killall netorcai`)
3. In terminal1, type some characters then type Ctrl+C, it should print `^C` instead of clearing the prompt line.

[![asciicast](https://asciinema.org/a/228561.svg)](https://asciinema.org/a/228561)

The issue also shows up when netorcai's prompt is exited by entering `quit`, but not when Ctrl+C is used...

**Comment by mpoquet** [comment]
Does 54fbf00 fix your issue?

[![asciicast](https://asciinema.org/a/228565.svg)](https://asciinema.org/a/228565)

**Comment by zephyr111** [comment]
It seems OK. Thank you.
Lets close the issue for now.
